### ISSUE TITLE
The return value from appending a node is unexpected

### ISSUE THREAD

**Issue by bronco-creek** [raku-community-modules/XML#19]
When I iteratively append new nodes to a node set, the return value of append() is the stringified concatenation of all of the nodes that have been appended up to that iteration.  For example, given

for @array-of-nodes -> $node {
    my $test = $nodeset.append($node);
    say "$test";
}

The value output for $test on the first iteration is the first $node stringified, on the next iteration, it is the the string from the first iteration concatenated with the string from the second, etc.

**Comment by supernovus** [comment]
That's definitely strange. It's been a while since I looked at this code. I will take a look shortly.

**Comment by jonathanstowe** [comment]
For reference it returns the newly amend `@.nodes` of the Element, which, as it is being stringified above will appear to be the stringified elements.  `say $test.raku` will show what is going on.

Unless someone considers that the behaviour should be different I would be minded to close this.

**Comment by JJ** [comment]
Please go ahead and close it.
