### ISSUE TITLE
Accept IO::Path as filename

### ISSUE THREAD

**Issue by Altreus** [raku-community-modules/XML#66]
Raku uses IO::Path to represent filenames so it would make sense that functions accept an IO::Path wherever a filename is expected

```
[0] > my $svg = dir('.', test => *.ends-with('.svg'))[0];
"thumbnail.svg".IO
[1] > from-xml-file($svg)
Type check failed in binding to parameter '$file'; expected Str but got IO::Path (IO::Path.new("thumbn...)
```

**Comment by 2colours** [comment]
Yes, indeed it would make sense. I find it somewhat counter-intuitive to call an IO::Path object a "filename" but at the end of the day it can even be coerced from a Str. I'm gonna look into it.
